rename libx264/libx265 binary

diff --git a/external/scripts/ffmpeg-config b/external/scripts/ffmpeg-config
--- a/external/scripts/ffmpeg-config
+++ b/external/scripts/ffmpeg-config
@@ -45,8 +45,7 @@ case "$PKG_CONFIG_PATH" in
 esac
 
 echo "PKG CONFIG Check Point"
-pkg-config --modversion x264
-pkg-config --cflags --libs x264
+pkg-config --modversion x264 || echo "x264 not found"
 
 echo Using ffmpeg options: $OPTIONS "$@"
 
@@ -55,4 +54,4 @@ cd "$BUILD"/ffmpeg_build
 # need to link against stdc++ in case libplacebo was built with glslang,
 # which requires that
 export LDFLAGS="$LDFLAGS -lstdc++"
-PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:/home/runner/work/libmpv-linux-build/libmpv-linux-build/dep/linux_amd64/lib/pkgconfig" "$BUILD"/ffmpeg/configure --prefix="$BUILD"/build_libs $OPTIONS "$@"
+"$BUILD"/ffmpeg/configure --prefix="$BUILD"/build_libs $OPTIONS "$@"
